language: node_js
node_js:
  - 6

cache:
  directories:
    - node_modules

before_script:
    - echo "About to deploy"

script:
    - echo "Deploying !"
    - npm install

install:
    - npm install -g firebase-tools

after_success:
    - echo "Successfully deployed"
    - firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
  - master

notifications:
  email: false
