language: node_js
node_js:
  - 6

cache:
  directories:
    - node_modules

before_script:
    - echo "About to deploy"

script:
    - echo "Deploying !"

after_success:
    - echo "Successfully deployed"

branches:
  only:
  - master

notifications:
  email: false
